scraper/src/config/config_validator.py, scraper/src/index.py, scraper/src/meilisearch_helper.py, scraper/src/tests/config_loader/abstract.py
Using the custom settings to give the desired settings they will be added before documentation addition on every scrap
The error handling on the settings should stay there until the Python SDK has a proper error handler. 
fixes: #14
=> Immutable settings

scraper/src/config/config_loader.py, scraper/src/meilisearch_helper.py, scraper/src/tests/config_loader/abstract.py
Fixes: #26 
Scenarios: 
- No `custom_settings`: ✅
- Good `custom_settings`: ✅
- Non existing `custom_settings` attributes : MeiliSearch returns a 400 `Bad Request`
- Bad type for `custom_settings`: Doc scraper returns an error  
```
Exception: custom_settings must be a dictionary
```
=> Fixes bug with custom settings

scraper/src/meilisearch_helper.py
Empty fields in documents are filled with 'null' string. I do not think this is a wanted behavior and we do have this issue when searching for null on docs.meilisearch.com
here are the results with the fix
=> Remove unwanted transform for None value to 'null'

Pipfile, README.md, scraper/src/meilisearch_helper.py
**[This PR](https://github.com/meilisearch/meilisearch-python/pull/88) needs to be merged and the package to be released before merging this PR.**
=> Update meilisearch-python version following MeiliSearch bump to v0.11

Pipfile, Pipfile.lock, scraper/src/documentation_spider.py
Remove this fatal error from `master` and temporarily fixes #64
=> Downgrade Scrapy from 2.3.0 to 2.2.1 because of NotImplementedError

Pipfile, Pipfile.lock, README.md, scraper/src/index.py
This PR add the ability to authenticate by Keycloak.
=> Add authentication with Keycloak for scraping

Pipfile, Pipfile.lock, README.md
This PR:
- gathers the changes related to the next release of MeiliSearch (v0.16.0) so that this package is ready when the official release is out.
- should pass the tests against the [latest prerelease of MeiliSearch](https://github.com/meilisearch/MeiliSearch/releases). This should be tested locally.
- might eventually fail until the MeiliSearch v0.16.0 is out.
⚠️ This PR should NOT be merged until the MeiliSearch's next release (v0.16.0) is out.
=> Changes about the MeiliSearch's next release (v0.16.0)

.gitignore, README.md
=> Adding config info to allow urls with ports

.gitignore, scraper/src/config/config_loader.py, scraper/src/documentation_spider.py
In both cases where I removed the `sys.exit` line there is a `raise` immediately preceding it so it is impossible to reach the `sys.exit`
=> Removed unreachable code

.github/workflows/tests.yml, .gitignore, CONTRIBUTING.md, Pipfile, Pipfile.lock, README.md, bors.toml, tox.ini
=> Adding support for Python 3.9

scraper/src/meilisearch_helper.py
Related to https://github.com/meilisearch/MeiliSearch/discussions/1766
=> Fix asc/desc syntax: make it work for MeiliSearch v0.22.0 and later

Dockerfile
Following the discussions about this issue https://github.com/meilisearch/docs-scraper/issues/139 and after running this #165 locally, I had some trouble using `chrome_webdriver` because my `Dockerfile` didn't have this package.
This is not a fix for the mentioned issue, is just a small part of it!
=> Add libnss3 package to Dockerfile

scraper/src/meilisearch_helper.py
The index should be deleted before the start of a new scraping. This is important as we do not want to keep scrapped page that does not exists anymore.
=> Fix: Delete index before starting scrapping

Dockerfile, Pipfile
Fixes #185 (**1 task**)
Dockerfile was updated as follows:
1. **Chromium-driver** was installed using [debian repo](https://packages.debian.org/buster/chromium-driver).
2. The speed of build process was optimized by leveraging build cache ([more](https://docs.docker.com/develop/develop-images/dockerfile_best-practices/#leverage-build-cache)). 
Please check if your PR fulfills the following requirements:
Hope you're doing great,
Matthew
=> Chromium-driver binary is added to Dockerfile 

scraper/src/index.py
This pr fixes the authorization header when authenticating against resources protected by gatekeeper.
According to https://datatracker.ietf.org/doc/html/rfc6750#section-2.1 the authorization header must follow the convention `Authorization: Bearer <token>`
=> Using 'Authorization: Bearer' according to rfc6750

Dockerfile, Pipfile, Pipfile.lock
The `chromedriver` version required by docs-scraper was not compatible with the chromedriver version in the previous python image `3.8.4` in the DockerFile.
Updating to latest `python:3.10.8-slim-bullseye` fixes this issue.
Additionally, the `requests` package is not a standard library so it should be explicitly added to the Pipfile.
We did not update to [`python:3.11.0-slim-bullseye`](https://hub.docker.com/layers/library/python/3.11.0-slim-bullseye/images/sha256-b59417e37f49eaf8f60a68193f1b27ea4f4c996394e88535b45509c8322a0f8a?context=explore) because selenium is using a package that is not compatible with 3.11. This will be fixed in another issue. See #285
=> Update python version in DockerFile to 3.10.8-slim-bullseye

scraper/src/strategies/abstract_strategy.py
Currently when running doc-scraper this error occur:
```sh
2023-03-14 12:10:56 [scrapy.core.scraper] ERROR: Spider error processing <GET https://docs.meilisearch.com/learn/advanced/geosearch.html> (referer: https://docs.meilisearch.com/sitemap.xml)
Traceback (most recent call last):
File "/Users/amelielallemand/.local/share/virtualenvs/docs-scraper-vWaWSN46/lib/python3.9/site-packages/twisted/internet/defer.py", line 892, in _runCallbacks
current.result = callback(  # type: ignore[misc]
File "/Users/amelielallemand/Projects/meili/repo/docs-scraper/scraper/src/documentation_spider.py", line 170, in parse_from_sitemap
self.add_records(response, from_sitemap=True)
File "/Users/amelielallemand/Projects/meili/repo/docs-scraper/scraper/src/documentation_spider.py", line 151, in add_records …
```
=> Try to fix Scrapy ERROR: Spider error processing

tests/config_files_examples/docs-basics.config.json, tests/config_files_examples/docs-custom.config.json
The new documentation website has changed so the config file struct for the test wasn't working
=> Fix CI test with the new documentation data

README.md
We recently migrated the docs to a new website. Our new address is https://meilisearch.com/docs.
=> Update README with links to new docs website

.github/scripts/check-release.sh
@alallema I saw the publish to docker hub failed. I think the version check script should point to the version file for `docs-scraper` and not `meilisearch-python`?
Fixes #<issue_number>
- Updates the path to the version file
Please check if your PR fulfills the following requirements:
Thank you so much for contributing to Meilisearch!
=> Update version file path

tests/meilisearch_helper/meilisearch_helper_test.py
@alallema we basically had the same idea. Since we know the expected format my thinking here is the first item in the list should start with `Meilisearch Python (`, then the specific version is already tested in `meilisearch-python` so we can trust that is correct.
Discussed in #396
- Makes it where the test won't fail with every update to `meilisearch-python`
Please check if your PR fulfills the following requirements:
Thank you so much for contributing to Meilisearch!
=> Refactor version test

.github/workflows/tests.yml, scraper/src/js_executor.py, tests/config_loader/get_extra_facets_test.py, tests/config_loader/open_selenium_browser_test.py, tests/config_loader/start_urls_test.py
@alallema I saw the publish to docker hub failed. I think the version check script should point to the version file for `docs-scraper` and not `meilisearch-python`?
Fixes #177
- Adds the chromedriver tests back to CI
Please check if your PR fulfills the following requirements:
Thank you so much for contributing to Meilisearch!
=> Add back chromedriver tests

.github/dependabot.yml
Change dependabot configuration to monthly.
Related to: https://github.com/meilisearch/integration-guides/issues/283
=> Update dependabot updates interval to monthly
